#!/usr/bin/env bash
set -e

cd /var/www

# --- Make nginx listen on Railway's $PORT ---
LISTEN_PORT="${PORT:-80}"
mkdir -p /opt/docker/etc/nginx/vhost.common.d
cat > /opt/docker/etc/nginx/vhost.common.d/00-listen.conf <<EOF
# Autogenerated by entrypoint: force nginx to listen on \$PORT
listen ${LISTEN_PORT};
listen [::]:${LISTEN_PORT};
EOF
# -------------------------------------------

# If APP_KEY is empty, generate one (idempotent)
if [ -z "${APP_KEY:-}" ]; then
  php artisan key:generate --force || true
fi

# Safe to re-run
php artisan storage:link >/dev/null 2>&1 || true

# Build caches; ignore if any provider touches DB/extensions not ready
php artisan config:cache  || true
php artisan route:cache   || true
php artisan view:cache    || true

# Hand over to base (runs nginx + php-fpm via supervisord)
exec "$@"
